/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e3e2e0",
        background: "#faf9f7",
        "surface-container-low": "#f4f3f1",
        "secondary-fixed": "#d1e4fb",
        "surface-dim": "#dadad8",
        "on-error": "#ffffff",
        surface: "#faf9f7",
        "inverse-primary": "#ffb595",
        "primary-fixed": "#ffdbcd",
        error: "#ba1a1a",
        "on-background": "#1a1c1b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001a41",
        "secondary-fixed-dim": "#b5c8df",
        "on-error-container": "#93000a",
        "surface-bright": "#faf9f7",
        "on-tertiary-container": "#fefcff",
        "tertiary-container": "#0070ec",
        "primary-container": "#c64f00",
        outline: "#8c7166",
        "primary-fixed-dim": "#ffb595",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed": "#091d2e",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#adc6ff",
        "on-secondary": "#ffffff",
        "surface-tint": "#a23f00",
        "surface-container": "#efeeec",
        tertiary: "#0058bd",
        "error-container": "#ffdad6",
        "on-surface-variant": "#594238",
        "on-primary": "#ffffff",
        "secondary-container": "#cfe2f9",
        "on-primary-fixed-variant": "#7c2e00",
        "on-secondary-fixed-variant": "#36485b",
        "on-tertiary-fixed-variant": "#004494",
        secondary: "#4e6073",
        "outline-variant": "#e0c0b2",
        "on-secondary-container": "#526478",
        primary: "#9e3d00",
        "surface-container-highest": "#e3e2e0",
        "on-primary-fixed": "#351000",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e8e6",
        "on-surface": "#1a1c1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        gutter: "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
